# eustasy Normalized Checks 1.10.0

dist: trusty
sudo: required

# https://secure.php.net/supported-versions.php
language: php
php:
  - 7.3
  - 7.4

before_script:
  - git clone https://github.com/eustasy/normal-checks.git
  - cd normal-checks
  - git checkout b92da74ddf4b05b698e2d12ebd56e965d6749397
  - cd ../
  - npm install --silent -g npm
  - npm install --silent -g acorn

script:
  - ./normal-checks/check-config.sh
  - ./normal-checks/check-permissions.sh
  - ./normal-checks/check-javascript.sh
  - ./normal-checks/check-php.sh
  - php normal-checks/check-json.php
  - php normal-checks/check-xml.php

notifications:
  email:
    recipients:
      - lewis.goddard@eustasy.org
    on_success: change
    on_failure: change
