name: Build CSS distributables

on:
  push:
    branches:
      - master
      - v2
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0/20 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run build and commit changes
      run: |
        echo "Running build..."
        python utils/generator.py
        echo "Setting up git credentials..."
        git remote set-url origin https://x-access-token:"$GITHUB_TOKEN"@github.com/"$GITHUB_REPOSITORY".git
        git config --global user.email "actions@github.com"
        git config --global user.name "actions"
        echo "Git credentials configured."
        git checkout master
        git add .
        git commit -m "Automatic build of CSS from data" && git push --set-upstream origin master || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
